In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
%load_ext autotime

time: 0 ns


# BlenderCNN

In [3]:
from keras.models import Sequential
from keras.layers import Input, Conv2DTranspose, BatchNormalization, LeakyReLU, Activation, Dense, Reshape
from keras.activations import sigmoid

time: 2.39 s


In [2]:
import os
import json
with open(os.path.expanduser(f'~/data/flying_dots/metadata.json'), 'r') as f:
    all_features = json.load(f)

In [3]:
import numpy as np
x = np.asarray(all_features['sample_1'], dtype=float)
x

array([ 0.8178674 ,  0.6382826 ,  0.18252081,  0.19351982, -0.82517093])

In [4]:
model = Sequential(name='name')
    
# Input
model.add(Reshape((1, 1, 5), input_dim=5, name='reshape'))

# Layer 1
model.add(Conv2DTranspose(
        filters=512,
        kernel_size=(4, 4),
        strides=(1, 1),
        use_bias=False,
        name=f'conv2d_t_layer1',
))
model.add(BatchNormalization(
        momentum=0.1,
        epsilon=1e-5,
        name=f'batch_norm_layer1',
))
model.add(LeakyReLU(
        name=f'leaky_relu_layer1',
))

# Layer 2
model.add(Conv2DTranspose(
        filters=256,
        kernel_size=(4, 4),
        strides=(2, 2),
        padding='same',
        use_bias=False,
        name=f'conv2d_t_layer2',
))
model.add(BatchNormalization(
        momentum=0.1,
        epsilon=1e-5,
        name=f'batch_norm_layer2',
))
model.add(LeakyReLU(
        name=f'leaky_relu_layer2',
))

# Layer 3
model.add(Conv2DTranspose(
        filters=128,
        kernel_size=(4, 4),
        strides=(2, 2),
        padding='same',
        use_bias=False,
        name=f'conv2d_t_layer3',
))
model.add(BatchNormalization(
        momentum=0.1,
        epsilon=1e-5,
        name=f'batch_norm_layer3',
))
model.add(LeakyReLU(
        name=f'leaky_relu_layer3',
))

# Layer 4
model.add(Conv2DTranspose(
        filters=64,
        kernel_size=(4, 4),
        strides=(2, 2),
        padding='same',
        use_bias=False,
        name=f'conv2d_t_layer4',
))
model.add(BatchNormalization(
        momentum=0.1,
        epsilon=1e-5,
        name=f'batch_norm_layer4',
))
model.add(LeakyReLU(
        name=f'leaky_relu_layer4',
))

# Layer 5
model.add(Conv2DTranspose(
        filters=32,
        kernel_size=(4, 4),
        strides=(2, 2),
        padding='same',
        use_bias=False,
        name=f'conv2d_t_layer5',
))
model.add(BatchNormalization(
        momentum=0.1,
        epsilon=1e-5,
        name=f'batch_norm_layer5',
))
model.add(LeakyReLU(
        name=f'leaky_relu_layer5',
))

# Layer 6
model.add(Conv2DTranspose(
        filters=16,
        kernel_size=(4, 4),
        strides=(2, 2),
        padding='same',
        use_bias=False,
        name=f'conv2d_t_layer6',
))
model.add(BatchNormalization(
        momentum=0.1,
        epsilon=1e-5,
        name=f'batch_norm_layer6',
))
model.add(LeakyReLU(
        name=f'leaky_relu_layer6',
))
    
# Final layer
model.add(Conv2DTranspose(
        filters=3,
        kernel_size=(2, 2),
        strides=(2, 2),
        output_padding=None,
        padding='same',
        use_bias=True,  # Enable bias since most values close to 0
        name='conv2d_t_last',
))
model.add(Activation(
        sigmoid,  # End with sigmoid layer to ensure values between 0..1
        name='sigmoid_last',
))
    
# Compile the model
model.compile(
        optimizer='adam',  # Adam optimiser
        loss='mse',  # Regression problem
)

model.summary()

Model: "name"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
reshape (Reshape)            (None, 1, 1, 5)           0         
_________________________________________________________________
conv2d_t_layer1 (Conv2DTrans (None, 4, 4, 512)         40960     
_________________________________________________________________
batch_norm_layer1 (BatchNorm (None, 4, 4, 512)         2048      
_________________________________________________________________
leaky_relu_layer1 (LeakyReLU (None, 4, 4, 512)         0         
_________________________________________________________________
conv2d_t_layer2 (Conv2DTrans (None, 8, 8, 256)         2097152   
_________________________________________________________________
batch_norm_layer2 (BatchNorm (None, 8, 8, 256)         1024      
_________________________________________________________________
leaky_relu_layer2 (LeakyReLU (None, 8, 8, 256)         0      

In [7]:
x = np.asarray([all_features['sample_1'],all_features['sample_2']], dtype=float)
x

array([[ 0.8178674 ,  0.6382826 ,  0.18252081,  0.19351982, -0.82517093],
       [ 0.88353854,  0.59632945,  0.18137495, -0.49492443,  0.33612549]])

time: 0 ns


In [8]:
model(x)

<tf.Tensor: shape=(2, 256, 256, 3), dtype=float32, numpy=
array([[[[0.5000003 , 0.50000006, 0.49999845],
         [0.49999946, 0.50000083, 0.49999917],
         [0.49999845, 0.5000006 , 0.49999702],
         ...,
         [0.49999356, 0.5000021 , 0.4999959 ],
         [0.4999984 , 0.5000001 , 0.4999981 ],
         [0.49999928, 0.50000054, 0.50000066]],

        [[0.50000054, 0.50000095, 0.5000008 ],
         [0.49999976, 0.50000125, 0.4999994 ],
         [0.49999833, 0.49999964, 0.49999976],
         ...,
         [0.49999952, 0.5000038 , 0.50000525],
         [0.4999997 , 0.50000083, 0.50000054],
         [0.5000002 , 0.50000125, 0.5000002 ]],

        [[0.49999928, 0.50000083, 0.5000026 ],
         [0.4999984 , 0.49999988, 0.50000083],
         [0.49999398, 0.500003  , 0.4999913 ],
         ...,
         [0.49999344, 0.50001043, 0.49999046],
         [0.49999684, 0.49999952, 0.5000025 ],
         [0.4999985 , 0.49999952, 0.49999893]],

        ...,

        [[0.49999803, 0.5000031 , 

time: 1.67 s


In [9]:
from generator import Generator
generator = Generator([f'sample_{i}' for i in range(1,101)])

Parsing images...: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 393.21it/s]

time: 375 ms


In [4]:
from sklearn.model_selection import train_test_split

from generator import Generator, parse_images
from model import TransposeCNN

time: 391 ms


In [5]:
# Load in datafiles
img_names = [f"sample_{i}" for i in range(1, 1001)]

time: 0 ns


In [6]:
x,y = parse_images(img_names)

Parsing images...: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1000/1000 [00:03<00:00, 257.20it/s]

time: 3.92 s


In [7]:
x.shape

(1000, 5)

time: 0 ns


In [16]:
import tensorflow as tf

config = tf.compat.v1.ConfigProto()
config.gpu_options.per_process_gpu_memory_fraction = 0.7
tf.compat.v1.keras.backend.set_session(tf.compat.v1.Session(config=config))

time: 1.16 s


In [17]:
model = TransposeCNN()

Model: "TransposeCNN"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
reshape (Reshape)            (None, 1, 1, 5)           0         
_________________________________________________________________
conv2d_t_layer1 (Conv2DTrans (None, 4, 4, 512)         40960     
_________________________________________________________________
batch_norm_layer1 (BatchNorm (None, 4, 4, 512)         2048      
_________________________________________________________________
leaky_relu_layer1 (LeakyReLU (None, 4, 4, 512)         0         
_________________________________________________________________
conv2d_t_layer2 (Conv2DTrans (None, 8, 8, 256)         2097152   
_________________________________________________________________
batch_norm_layer2 (BatchNorm (None, 8, 8, 256)         1024      
_________________________________________________________________
leaky_relu_layer2 (LeakyReLU (None, 8, 8, 256)        

C:\Users\Ruben\Documents\Projects\BlenderCNN\model.py:69: UserWarning: Model loaded successfully!
  warn("Model loaded successfully!")


In [19]:
# Train the model
model.model.fit(
    epochs=1,
    x=x,y=y,
)

32/32 [==============================] - 3s 84ms/step - loss: 0.1846


time: 6.23 s


In [12]:
from tqdm import tqdm

time: 0 ns


In [14]:
for i, x in enumerate(tqdm(range(10))):
    print(i,x)

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<?, ?it/s]

0 0
1 1
2 2
3 3
4 4
5 5
6 6
7 7
8 8
9 9
time: 0 ns


In [17]:
import numpy as np
x = np.zeros((2,2), dtype=float)
x

array([[0., 0.],
       [0., 0.]])

time: 0 ns


In [18]:
x[0,:] = [1,2]

time: 16 ms


In [19]:
x

array([[1., 2.],
       [0., 0.]])

time: 0 ns
